# Weights and biases
wandb_run: True
entity : "cs532-2022" #to post results -> 'cs532-2022', to analyze your own stuff -> 'williamlaplante'

# Directory structure
#CPSC532Homeworks
base_dir: '../CPSC532Homeworks/CPSC532-HW4' # NOTE: This path should be relative to the daphne path!
daphne_dir: '../../daphne' # NOTE: This path should be relative to the homework directory!

# Tests and programs to run
deterministic_tests: []
probabilistic_tests: []
HW4_programs: [4]

#which HW to run
prog_set: 'HW4'

# Daphne (re)compilation
compile: False

# Evaluation method
#mode: 'desugar'
mode: 'graph'

# Inference
num_samples: 1e4

BBVI : True

save : False