wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    session_history: code/_session_history.ipynb
    start_time: 1663813053.668686
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      4: 3.9.7
      5: 0.13.3
      8:
      - 1
      - 5
    visualize:
      Question 5; bias:
        panel_config:
          fieldSettings:
            value: bias
          panelDefId: wandb/histogram/v0
          stringSettings:
            title: Question 5; bias
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Question 5; bias_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      Question 5; scatter:
        panel_config:
          fieldSettings:
            x: slope
            y: bias
          panelDefId: wandb/scatter/v0
          stringSettings:
            title: Question 5; slope vs. bias
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Question 5; scatter_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      Question 5; slope:
        panel_config:
          fieldSettings:
            value: slope
          panelDefId: wandb/histogram/v0
          stringSettings:
            title: Question 5; slope
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Question 5; slope_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
