# Weights and biases
wandb_run: False

# Directory structure
base_dir: '../CPSC532-HW2' # NOTE: This path should be relative to the daphne path!
daphne_dir: '../../daphne' # NOTE: This path should be relative to the homework directory!

# Tests and programs to run
deterministic_tests: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
probabilistic_tests: [1, 2, 3, 4, 5, 6, 7, 8]
HW2_programs: [1, 2, 3, 4]

#which HW to run
prog_set: 'HW2'

# Daphne (re)compilation
compile: False

# Evaluation method
mode: 'desugar'
#mode: 'graph'

# Inference
num_samples: 1e3