wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    code_path: code/run.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1664652524.24221
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 5
      - 50
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.9.7
      5: 0.13.3
      8:
      - 5
      10:
      - 5
    visualize:
      Program 1:
        panel_config:
          fieldSettings:
            value: mu
          panelDefId: wandb/histogram/v0
          stringSettings:
            title: Program 1; mu
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Program 1_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      Program 2; bias:
        panel_config:
          fieldSettings:
            value: bias
          panelDefId: wandb/histogram/v0
          stringSettings:
            title: Program 2; bias
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Program 2; bias_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      Program 2; scatter:
        panel_config:
          fieldSettings:
            x: slope
            y: bias
          panelDefId: wandb/scatter/v0
          stringSettings:
            title: Program 2; slope vs. bias
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Program 2; scatter_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      Program 2; slope:
        panel_config:
          fieldSettings:
            value: slope
          panelDefId: wandb/histogram/v0
          stringSettings:
            title: Program 2; slope
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Program 2; slope_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      Program 4; mean:
        panel_config:
          fieldSettings:
            stroke: null
            x: position
            y: mean
          panelDefId: wandb/line/v0
          stringSettings:
            title: Program 4; mean
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Program 4; mean_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      Program 4; std:
        panel_config:
          fieldSettings:
            stroke: null
            x: position
            y: std
          panelDefId: wandb/line/v0
          stringSettings:
            title: Program 4; std
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Program 4; std_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
    viz:
      Program 3; heatmap:
        historyFieldSettings:
          key: Program 3; heatmap
          x-axis: _step
        id: wandb/heatmap/v1
